//! systemd (Linux) backend. The service runs as a systemd **user** unit at
//! `~/.config/systemd/user/ygrep.service`, driven with `systemctl --user`. Mirrors the
//! launchd backend's public API and its tolerate-absence semantics exactly.

use anyhow::{Context, Result};
use std::path::PathBuf;

#[cfg(target_os = "linux")]
use anyhow::bail;
#[cfg(target_os = "linux")]
use std::fs;
#[cfg(target_os = "linux")]
use std::process::{Command, Stdio};

use super::ServiceSpec;
#[cfg(target_os = "linux")]
use super::Status;

/// Unit name without the `.service` suffix.
const UNIT: &str = "ygrep";

pub fn label() -> &'static str {
    UNIT
}

/// Full systemd unit name.
fn unit_name() -> String {
    format!("{UNIT}.service")
}

fn unit_dir() -> Result<PathBuf> {
    let base = dirs::config_dir().context("Could not determine config directory")?;
    Ok(base.join("systemd/user"))
}

/// Path of the unit file that defines the service.
pub fn unit_path() -> Result<PathBuf> {
    Ok(unit_dir()?.join(unit_name()))
}

/// Run `systemctl --user <args>`, capturing output so nothing leaks into the TUI.
#[cfg(target_os = "linux")]
fn systemctl(args: &[&str]) -> Result<std::process::Output> {
    Command::new("systemctl")
        .arg("--user")
        .args(args)
        .stdin(Stdio::null())
        .output()
        .context("Failed to run systemctl --user")
}

#[cfg(target_os = "linux")]
fn daemon_reload() {
    let _ = systemctl(&["daemon-reload"]);
}

/// Escape one ExecStart token. systemd word-splits ExecStart on unquoted whitespace and
/// expands `%` specifiers, so every token is quoted and `\`, `"` and `%` are escaped.
fn systemd_quote(token: &str) -> String {
    let escaped = token
        .replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('%', "%%");
    format!("\"{escaped}\"")
}

/// `StandardOutput=append:` takes the rest of the line literally, so the value only has
/// to be free of newlines.
fn sanitize_path_value(path: &std::path::Path) -> String {
    path.display().to_string().replace('\n', " ")
}

/// Render the systemd user unit for a spec.
pub fn render_unit(spec: &ServiceSpec) -> String {
    let mut exec = systemd_quote(&spec.program.display().to_string());
    for arg in &spec.args {
        exec.push(' ');
        exec.push_str(&systemd_quote(arg));
    }
    let log = sanitize_path_value(&spec.log);

    let restart = if spec.keep_alive {
        "Restart=always\nRestartSec=2\n"
    } else {
        "Restart=no\n"
    };
    let install = if spec.run_at_load {
        "\n[Install]\nWantedBy=default.target\n"
    } else {
        ""
    };

    format!(
        "# Generated by ygrep — do not edit by hand.\n\
         [Unit]\n\
         Description=ygrep background watch service\n\
         \n\
         [Service]\n\
         Type=exec\n\
         ExecStart={exec}\n\
         {restart}\
         StandardOutput=append:{log}\n\
         StandardError=append:{log}\n\
         Environment=HOME=%h\n\
         {install}"
    )
}

/// Write the unit file, reload the manager, and enable it for login when the spec asks
/// for it. Starting happens in [`start`], mirroring launchd's write-then-load split.
#[cfg(target_os = "linux")]
pub fn install(spec: &ServiceSpec) -> Result<()> {
    let dir = unit_dir()?;
    fs::create_dir_all(&dir).with_context(|| format!("Failed to create {}", dir.display()))?;
    if let Some(parent) = spec.log.parent() {
        fs::create_dir_all(parent).ok();
    }
    let path = unit_path()?;
    fs::write(&path, render_unit(spec))
        .with_context(|| format!("Failed to write unit {}", path.display()))?;
    daemon_reload();
    if spec.run_at_load {
        // Creates the default.target.wants symlink without starting the unit.
        let _ = systemctl(&["enable", &unit_name()]);
    }
    Ok(())
}

/// Start the service.
#[cfg(target_os = "linux")]
pub fn start() -> Result<()> {
    let path = unit_path()?;
    if !path.exists() {
        bail!("The ygrep service is not installed. Run `ygrep service install` first.");
    }
    let out = systemctl(&["start", &unit_name()])?;
    if !out.status.success() {
        let stderr = String::from_utf8_lossy(&out.stderr);
        if !stderr.trim().is_empty() {
            bail!("systemctl --user start failed: {}", stderr.trim());
        }
    }
    Ok(())
}

/// Stop the service. Tolerates a missing or already-inactive unit.
#[cfg(target_os = "linux")]
pub fn stop() -> Result<()> {
    let path = unit_path()?;
    if !path.exists() {
        return Ok(());
    }
    let out = systemctl(&["stop", &unit_name()])?;
    if !out.status.success() {
        let stderr = String::from_utf8_lossy(&out.stderr);
        let benign = stderr.contains("not loaded")
            || stderr.contains("not active")
            || stderr.contains("not found");
        if !benign && !stderr.trim().is_empty() {
            bail!("systemctl --user stop failed: {}", stderr.trim());
        }
    }
    Ok(())
}

/// Restart. `systemctl restart` starts a stopped unit and re-reads the unit file that
/// `install` reloaded, so a rewritten `ExecStart` takes effect.
#[cfg(target_os = "linux")]
pub fn restart() -> Result<()> {
    let path = unit_path()?;
    if !path.exists() {
        bail!("The ygrep service is not installed. Run `ygrep service install` first.");
    }
    let out = systemctl(&["restart", &unit_name()])?;
    if !out.status.success() {
        let stderr = String::from_utf8_lossy(&out.stderr);
        if !stderr.trim().is_empty() {
            bail!("systemctl --user restart failed: {}", stderr.trim());
        }
    }
    Ok(())
}

/// Disable, stop, and delete the unit. Tolerates absence throughout.
#[cfg(target_os = "linux")]
pub fn uninstall() -> Result<()> {
    let path = unit_path()?;
    if path.exists() {
        let _ = systemctl(&["disable", "--now", &unit_name()]);
        fs::remove_file(&path)
            .with_context(|| format!("Failed to remove unit {}", path.display()))?;
        daemon_reload();
    }
    Ok(())
}

/// Report the service's state from `systemctl --user show -p ActiveState`.
#[cfg(target_os = "linux")]
pub fn status() -> Status {
    if !unit_path().map(|p| p.exists()).unwrap_or(false) {
        return Status::NotInstalled;
    }

    match systemctl(&["show", "-p", "ActiveState", "--value", &unit_name()]) {
        Ok(o) if o.status.success() => match String::from_utf8_lossy(&o.stdout).trim() {
            "active" | "activating" | "reloading" => Status::Running,
            "failed" => Status::Error,
            _ => Status::Stopped,
        },
        _ => Status::Stopped,
    }
}

/// The pid systemd reports for the service (`MainPID`); 0 means none.
#[cfg(target_os = "linux")]
pub fn pid() -> Option<u32> {
    let out = systemctl(&["show", "-p", "MainPID", "--value", &unit_name()]).ok()?;
    if !out.status.success() {
        return None;
    }
    match String::from_utf8_lossy(&out.stdout).trim().parse::<u32>() {
        Ok(0) | Err(_) => None,
        Ok(pid) => Some(pid),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn spec() -> ServiceSpec {
        ServiceSpec {
            program: PathBuf::from("/home/dev/.cargo/bin/ygrep"),
            args: vec!["service".into(), "run".into()],
            log: PathBuf::from("/home/dev/.local/share/ygrep/logs/service.log"),
            keep_alive: true,
            run_at_load: true,
        }
    }

    #[test]
    fn unit_carries_the_exec_line_log_and_install_section() {
        let unit = render_unit(&spec());

        assert!(unit.contains("Description=ygrep background watch service"));
        assert!(unit.contains("ExecStart=\"/home/dev/.cargo/bin/ygrep\" \"service\" \"run\"\n"));
        assert!(unit.contains("Restart=always"));
        assert!(
            unit.contains("StandardOutput=append:/home/dev/.local/share/ygrep/logs/service.log\n")
        );
        assert!(
            unit.contains("StandardError=append:/home/dev/.local/share/ygrep/logs/service.log\n")
        );
        assert!(unit.contains("[Install]\nWantedBy=default.target"));
    }

    #[test]
    fn unit_drops_restart_and_install_when_they_are_off() {
        let mut spec = spec();
        spec.keep_alive = false;
        spec.run_at_load = false;

        let unit = render_unit(&spec);

        assert!(unit.contains("Restart=no"));
        assert!(!unit.contains("[Install]"));
    }

    #[test]
    fn exec_tokens_are_quoted_and_percent_escaped() {
        assert_eq!(systemd_quote("plain"), "\"plain\"");
        assert_eq!(systemd_quote("with space"), "\"with space\"");
        assert_eq!(systemd_quote("100%"), "\"100%%\"");
        assert_eq!(systemd_quote(r#"a"b\c"#), r#""a\"b\\c""#);
    }

    #[test]
    fn the_unit_name_is_stable() {
        assert_eq!(label(), "ygrep");
        assert_eq!(unit_name(), "ygrep.service");
    }
}
